import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../core/models.dart';
import '../../widgets/app_scaffold.dart';
import '../../widgets/form_scaffold.dart';
import '../manager/vouchers/voucher_repository.dart';

class CreateVoucherScreen extends ConsumerStatefulWidget {
  const CreateVoucherScreen({super.key});

  @override
  ConsumerState<CreateVoucherScreen> createState() => _CreateVoucherScreenState();
}

class _CreateVoucherScreenState extends ConsumerState<CreateVoucherScreen> {
  final _formKey = GlobalKey<FormState>();

  String _code = '';
  String _type = 'percent';
  String _valueText = '';
  String _minOrderText = '';
  DateTime? _expiryDate;
  bool _isLoading = false;

  final _dateController = TextEditingController();

  @override
  void dispose() {
    _dateController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (_formKey.currentState?.validate() ?? false) {
      _formKey.currentState!.save();
      setState(() => _isLoading = true);

      try {
        final existing = await Supabase.instance.client
            .from('vouchers')
            .select('id')
            .eq('code', _code)
            .maybeSingle();

        if (existing != null) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Mã voucher này đã tồn tại, vui lòng chọn mã khác!')),
            );
          }
          setState(() => _isLoading = false);
          return;
        }

        final value = num.tryParse(_valueText) ?? 0;
        final minOrder = num.tryParse(_minOrderText) ?? 0;
        
        final voucher = VoucherModel(
          id: 0, // Generated by DB
          code: _code,
          type: _type == 'percent' ? VoucherType.percent : VoucherType.amount,
          value: value,
          minOrder: minOrder,
          expiryDate: _expiryDate,
          active: true,
        );

        await ref.read(voucherRepositoryProvider).createVoucher(voucher);
        if (mounted) Navigator.pop(context);
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Lỗi: $e')),
          );
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      title: 'Tạo mã giảm giá',
      body: Form(
        key: _formKey,
        child: FormScaffold(
          submitLabel: _isLoading ? 'Đang lưu...' : 'Lưu',
          onSubmit: _isLoading ? () {} : _submit,
          children: [
            const Text(
              'Mã voucher (VD: SUMMER20)',
              style: TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
            ),
            const SizedBox(height: 8),
            TextFormField(
              decoration: const InputDecoration(hintText: 'Nhập mã voucher'),
              validator: (value) => value == null || value.isEmpty ? 'Bắt buộc' : null,
              onSaved: (val) => _code = val ?? '',
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Loại giảm giá',
                        style: TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
                      ),
                      const SizedBox(height: 8),
                      DropdownButtonFormField<String>(
                        initialValue: _type,
                        items: const [
                          DropdownMenuItem(value: 'percent', child: Text('Phần trăm (%)')),
                          DropdownMenuItem(value: 'amount', child: Text('Số tiền (VNĐ)')),
                        ],
                        onChanged: (value) => _type = value ?? 'percent',
                        decoration: const InputDecoration(),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Giá trị',
                        style: TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        keyboardType: TextInputType.number,
                        decoration: const InputDecoration(hintText: 'Nhập giá trị'),
                        validator: (value) => value == null || value.isEmpty ? 'Bắt buộc' : null,
                        onSaved: (val) => _valueText = val ?? '0',
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            const Text(
              'Đơn tối thiểu (VNĐ)',
              style: TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
            ),
            const SizedBox(height: 8),
            TextFormField(
              keyboardType: TextInputType.number,
              decoration: const InputDecoration(hintText: 'Nhập giá trị (nếu có)'),
              onSaved: (val) => _minOrderText = val ?? '0',
            ),
            const SizedBox(height: 16),
            const Text(
              'Hạn sử dụng',
              style: TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
            ),
            const SizedBox(height: 8),
            TextFormField(
              controller: _dateController,
              decoration: const InputDecoration(
                hintText: 'DD/MM/YYYY',
                suffixIcon: Icon(Icons.calendar_today_outlined),
              ),
              readOnly: true,
              onTap: () async {
                final date = await showDatePicker(
                  context: context,
                  initialDate: DateTime.now(),
                  firstDate: DateTime.now(),
                  lastDate: DateTime(2030),
                );
                if (date != null) {
                  setState(() {
                    _expiryDate = date;
                    _dateController.text = DateFormat('dd/MM/yyyy').format(date);
                  });
                }
              },
            ),
          ],
        ),
      ),
    );
  }
}
